# Generated by Django 4.2.6 on 2024-03-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='webpage',
            name='ename',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.AddField(
            model_name='accessrecords',
            name='ename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.webpage'),
        ),
    ]
